// Copyright RiftbornAI. All Rights Reserved.
// Example: Simple AI Character with Health Component
// Generated by RiftbornAI - DO NOT MODIFY HEADER

#include "ExampleAICharacter.h"
#include "AbilitySystemComponent.h"
#include "HealthAttributeSet.h"

AExampleAICharacter::AExampleAICharacter()
{
    PrimaryActorTick.bCanEverTick = true;

    // Create Ability System Component
    AbilitySystemComponent = CreateDefaultSubobject<UAbilitySystemComponent>(TEXT("AbilitySystemComp"));
    AbilitySystemComponent->SetIsReplicated(true);
    AbilitySystemComponent->SetReplicationMode(EGameplayEffectReplicationMode::Mixed);

    // Health Attributes will be added on BeginPlay
}

void AExampleAICharacter::BeginPlay()
{
    Super::BeginPlay();

    // Initialize GAS
    if (AbilitySystemComponent)
    {
        AbilitySystemComponent->InitAbilityActorInfo(this, this);
        
        // Create and register attribute set
        HealthAttributes = NewObject<UHealthAttributeSet>(this);
        AbilitySystemComponent->AddAttributeSetSubobject(HealthAttributes);
    }
}

UAbilitySystemComponent* AExampleAICharacter::GetAbilitySystemComponent() const
{
    return AbilitySystemComponent;
}

float AExampleAICharacter::GetHealth() const
{
    if (HealthAttributes)
    {
        return HealthAttributes->GetHealth();
    }
    return 0.0f;
}

float AExampleAICharacter::GetMaxHealth() const
{
    if (HealthAttributes)
    {
        return HealthAttributes->GetMaxHealth();
    }
    return 100.0f;
}

bool AExampleAICharacter::IsAlive() const
{
    return !bIsDead && GetHealth() > 0.0f;
}

void AExampleAICharacter::ApplyDamage(float DamageAmount, AActor* DamageCauser)
{
    if (bIsDead || DamageAmount <= 0.0f)
    {
        return;
    }

    const float OldHealth = GetHealth();
    const float NewHealth = FMath::Max(0.0f, OldHealth - DamageAmount);

    if (HealthAttributes)
    {
        HealthAttributes->SetHealth(NewHealth);
    }

    OnHealthChanged(OldHealth, NewHealth);

    if (NewHealth <= 0.0f)
    {
        bIsDead = true;
        OnDeath();
    }
}

void AExampleAICharacter::Heal(float HealAmount)
{
    if (bIsDead || HealAmount <= 0.0f)
    {
        return;
    }

    const float OldHealth = GetHealth();
    const float NewHealth = FMath::Min(GetMaxHealth(), OldHealth + HealAmount);

    if (HealthAttributes)
    {
        HealthAttributes->SetHealth(NewHealth);
    }

    OnHealthChanged(OldHealth, NewHealth);
}

void AExampleAICharacter::OnDeath_Implementation()
{
    // Default death behavior - disable collision and movement
    GetCapsuleComponent()->SetCollisionEnabled(ECollisionEnabled::NoCollision);
    GetCharacterMovement()->DisableMovement();
    
    // Notify Behavior Tree (if using)
    // Could also trigger ragdoll, death animation, etc.
}

void AExampleAICharacter::OnHealthChanged_Implementation(float OldHealth, float NewHealth)
{
    // Override in Blueprint or subclass for visual feedback
    // E.g., damage numbers, health bar updates, hit reactions
}
