// Copyright RiftbornAI. All Rights Reserved.
// Example: Simple AI Character with Health Component
// Generated by RiftbornAI - DO NOT MODIFY HEADER

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Character.h"
#include "AbilitySystemInterface.h"
#include "ExampleAICharacter.generated.h"

class UAbilitySystemComponent;
class UHealthAttributeSet;

/**
 * Example AI Character demonstrating RiftbornAI code generation.
 * 
 * Features:
 * - GAS integration with AbilitySystemComponent
 * - Health attribute with damage/healing
 * - Death handling
 * - Simple patrol behavior ready for Behavior Tree
 * 
 * Generated with: "Create an AI character with 100 health that can patrol"
 */
UCLASS()
class AExampleAICharacter : public ACharacter, public IAbilitySystemInterface
{
    GENERATED_BODY()

public:
    AExampleAICharacter();

    // IAbilitySystemInterface
    virtual UAbilitySystemComponent* GetAbilitySystemComponent() const override;

    /** Get current health value */
    UFUNCTION(BlueprintPure, Category = "Health")
    float GetHealth() const;

    /** Get maximum health value */
    UFUNCTION(BlueprintPure, Category = "Health")
    float GetMaxHealth() const;

    /** Check if character is alive */
    UFUNCTION(BlueprintPure, Category = "Health")
    bool IsAlive() const;

    /** Apply damage to this character */
    UFUNCTION(BlueprintCallable, Category = "Health")
    void ApplyDamage(float DamageAmount, AActor* DamageCauser);

    /** Heal this character */
    UFUNCTION(BlueprintCallable, Category = "Health")
    void Heal(float HealAmount);

protected:
    virtual void BeginPlay() override;

    /** Called when health reaches zero */
    UFUNCTION(BlueprintNativeEvent, Category = "Health")
    void OnDeath();

    /** Called when health changes */
    UFUNCTION(BlueprintNativeEvent, Category = "Health")
    void OnHealthChanged(float OldHealth, float NewHealth);

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Abilities")
    TObjectPtr<UAbilitySystemComponent> AbilitySystemComponent;

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Attributes")
    TObjectPtr<UHealthAttributeSet> HealthAttributes;

    /** Patrol waypoints for AI behavior */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AI|Patrol")
    TArray<FVector> PatrolPoints;

    /** Current patrol index */
    UPROPERTY(BlueprintReadOnly, Category = "AI|Patrol")
    int32 CurrentPatrolIndex = 0;

    /** Detection range for player awareness */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "AI|Perception")
    float DetectionRange = 1000.0f;

private:
    bool bIsDead = false;
};
