// Copyright RiftbornAI. All Rights Reserved.
// Shared includes for ToolImpl_*.cpp satellite files
// These files contain FRiftbornBuiltinTools::Tool_* method implementations
// extracted from ClaudeToolUse.cpp during H1b decomposition.

#pragma once

#include "ClaudeToolUse.h"
#include "DebugBridgeServer.h"
#include "RiftbornLog.h"   // RIFTBORN_LOG / RIFTBORN_LOG_WARNING used by every ToolImpl_*.cpp
#include "LatentJobExecutor.h"
#include "RiftbornSafeExecution.h"
#include "Tools/BatchToolsModule.h"
#include "RiftbornSettings.h"
#include "BlueprintGraphEditor.h"
#include "BlueprintGraphAPI.h"
#include "BrainMetrics.h"
#include "ToolContract.h"
#include "ReadOnlyToolsWhitelist.h"
#include "ToolExecutionBroadcaster.h"
#include "SessionTaint.h"
#include "ExecCtxValidator.h"
#include "ProofWriter.h"
#include "ClaimTypes.h"
#include "ErrorMessageEnhancer.h"
#include "InputSanitization.h"
#include "ProjectAssetIndex.h"
#include "HotReloadIntegration.h"
#include "ToolImplHelpers.h"
#include "CppCodeGenerator.h"
#include "ActionHistory.h"
#include "ConversationMemory.h"
#include "PerformanceMetrics.h"
#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "Serialization/JsonWriter.h"
#include "EditorAssetLibrary.h"
#include "EditorLevelLibrary.h"
#include "Subsystems/EditorActorSubsystem.h"
#include "EngineUtils.h"
#include "Engine/Blueprint.h"
#include "GameFramework/Actor.h"
#include "GameFramework/GameModeBase.h"
#include "GameFramework/WorldSettings.h"
#include "GameFramework/PlayerController.h"
#include "GameFramework/Pawn.h"
#if RIFTBORN_WITH_PYTHON
#include "IPythonScriptPlugin.h"
#endif
#include "Misc/FileHelper.h"
#include "HAL/PlatformFileManager.h"
#include "Internationalization/Regex.h"
#include "Editor.h"
#include "Selection.h"
#include "Engine/StaticMesh.h"
#include "Engine/StaticMeshActor.h"
#include "Engine/SkeletalMesh.h"
#include "Engine/DataTable.h"
#include "Engine/LevelStreaming.h"
#include "Components/StaticMeshComponent.h"
#include "Components/SkeletalMeshComponent.h"
#include "Components/PrimitiveComponent.h"
#include "Components/AudioComponent.h"
#include "Materials/Material.h"
#include "Materials/MaterialInterface.h"
#include "Materials/MaterialInstanceConstant.h"
#include "Factories/MaterialFactoryNew.h"
#include "AssetToolsModule.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "Misc/SecureHash.h"
#include "RiftbornCrypto.h"
#include "FileHelpers.h"
#include "EditorActorFolders.h"
#include "LevelEditorSubsystem.h"
#if WITH_EDITOR
#include "LevelEditorViewport.h"
#endif
#include "Settings/LevelEditorPlaySettings.h"
#include "Kismet/GameplayStatics.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "K2Node_CustomEvent.h"
#include "K2Node_CallFunction.h"
#include "K2Node_VariableGet.h"
#include "K2Node_VariableSet.h"
#include "EdGraphSchema_K2.h"
#include "BlueprintTypeUtils.h"
#include "Logging/TokenizedMessage.h"
#include "Engine/Texture2D.h"
#include "AutomatedAssetImportData.h"
#include "UObject/SavePackage.h"
#include "ObjectTools.h"
#include "Animation/AnimSequence.h"
#include "Animation/AnimComposite.h"
#include "Animation/BlendSpace1D.h"
#include "Sound/SoundCue.h"
#include "Sound/SoundWave.h"
#include "WidgetBlueprint.h"
#include "Blueprint/UserWidget.h"

// Plugin headers for data assets, asset pipeline, tool utilities
#include "RiftbornDataAsset.h"
#include "AssetPipeline.h"
#include "Tools/ToolUtils.h"

// Landscape
#include "Landscape.h"
#include "LandscapeProxy.h"

// Engine systems
#include "GameFramework/Character.h"
#include "Perception/AIPerceptionComponent.h"
#include "Interfaces/IPluginManager.h"
#include "Interfaces/IProjectManager.h"
#include "ISourceControlModule.h"
