// GetActorInfoStructuredToolsModule.h
// Auto-generated tool module for world.get_actor_info_structured
// Generated by ToolGapResolver

#pragma once

#include "CoreMinimal.h"
#include "ClaudeToolUse.h"
#include "Tools/ToolModuleBase.h"

/**
 * GetActorInfoStructuredToolsModule Module
 *
 * Get actor info with structured output. Returns stable, deterministic JSON.
 *
 * Capability: world.get_actor_info_structured
 * Mutates: No
 * Deterministic: Yes
 */
class RIFTBORNAI_API FGetActorInfoStructuredToolsModuleModule : public TToolModuleBase<FGetActorInfoStructuredToolsModuleModule>
{
public:
    static FString StaticModuleName() { return TEXT("GetActorInfoStructuredToolsModule"); }

    virtual void RegisterTools(FClaudeToolRegistry& Registry) override;

    // Tool implementation
    static FClaudeToolResult Tool_GetActorInfoStructured(const FClaudeToolCall& Call);
    static FClaudeToolResult Tool_InspectActor(const FClaudeToolCall& Call);

private:
    // Helper to find actor by path
    static AActor* FindActorByPath(UWorld* World, const FString& ActorPath);
};
