// GetActorComponentsStructuredToolsModule.h
// Auto-generated tool module for world.get_actor_components_structured
// Generated by ToolGapResolver

#pragma once

#include "CoreMinimal.h"
#include "ClaudeToolUse.h"
#include "Tools/ToolModuleBase.h"

/**
 * GetActorComponentsStructuredToolsModule Module
 * 
 * Get all components on an actor with structured output. Returns stable, deterministic JSON. REQUIRES property_whitelist when include_properties=true.
 * 
 * Capability: world.get_actor_components_structured
 * Mutates: No
 * Deterministic: Yes
 */
class RIFTBORNAI_API FGetActorComponentsStructuredToolsModuleModule : public TToolModuleBase<FGetActorComponentsStructuredToolsModuleModule>
{
public:
    static FString StaticModuleName() { return TEXT("GetActorComponentsStructuredToolsModule"); }
    
    virtual void RegisterTools(FClaudeToolRegistry& Registry) override;
    
    // Tool implementation
    static FClaudeToolResult Tool_GetActorComponentsStructured(const FClaudeToolCall& Call);
    
private:
    // Helper to find actor by path
    static AActor* FindActorByPath(UWorld* World, const FString& ActorPath);
};

