// GetComponentPropertiesStructuredToolsModule.h
// Auto-generated tool module for world.get_component_properties_structured
// Generated by ToolGapResolver

#pragma once

#include "CoreMinimal.h"
#include "ClaudeToolUse.h"
#include "Tools/ToolModuleBase.h"

/**
 * GetComponentPropertiesStructuredToolsModule Module
 * 
 * Get specific properties from a component with typed values. Returns deterministic JSON.
 * 
 * Capability: world.get_component_properties_structured
 * Mutates: No
 * Deterministic: Yes
 */
class RIFTBORNAI_API FGetComponentPropertiesStructuredToolsModuleModule : public TToolModuleBase<FGetComponentPropertiesStructuredToolsModuleModule>
{
public:
    static FString StaticModuleName() { return TEXT("GetComponentPropertiesStructuredToolsModule"); }
    
    virtual void RegisterTools(FClaudeToolRegistry& Registry) override;
    
    // Tool implementation
    static FClaudeToolResult Tool_GetComponentPropertiesStructured(const FClaudeToolCall& Call);
    
private:
    // Helper to find actor by path
    static AActor* FindActorByPath(UWorld* World, const FString& ActorPath);
    // Helper to find component by full path/id
    static UActorComponent* FindComponentByPath(UWorld* World, const FString& ComponentPath);
};
