// SetComponentPropertyTypedToolsModule.h
// Auto-generated tool module for world.set_component_property_typed
// Generated by ToolGapResolver

#pragma once

#include "CoreMinimal.h"
#include "ClaudeToolUse.h"
#include "Tools/ToolModuleBase.h"

/**
 * SetComponentPropertyTypedToolsModule Module
 * 
 * Set a component property with typed validation and undo support
 * 
 * Capability: world.set_component_property_typed
 * Mutates: Yes
 * Deterministic: Yes
 */
class RIFTBORNAI_API FSetComponentPropertyTypedToolsModuleModule : public TToolModuleBase<FSetComponentPropertyTypedToolsModuleModule>
{
public:
    static FString StaticModuleName() { return TEXT("SetComponentPropertyTypedToolsModule"); }
    
    virtual void RegisterTools(FClaudeToolRegistry& Registry) override;
    
    // Tool implementation
    static FClaudeToolResult Tool_SetComponentPropertyTyped(const FClaudeToolCall& Call);
    
private:
    // Helper to find actor by path
    static AActor* FindActorByPath(UWorld* World, const FString& ActorPath);
};